version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    container_name: real-estate-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv

  streamlit:
    build:
      context: .
      dockerfile: dockerfile.streamlit
    container_name: real-estate-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./app.py:/app/app.py

    depends_on:
      - api
